---
  repos:
    - repo: https://github.com/commit-check/commit-check
      rev: v0.8.5
      hooks:
      -   id: check-message
      -   id: check-branch
      -   id: check-author-name
      -   id: check-author-email
